name: google_ml_kit
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: '>=3.0.6 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  image_picker: ^1.0.2
  camera: ^0.10.5+2
  path: ^1.8.3
  path_provider: ^2.1.0
  google_mlkit_barcode_scanning: ^0.9.0
  google_mlkit_commons: ^0.5.0
  google_mlkit_digital_ink_recognition: ^0.9.0
  google_mlkit_entity_extraction: ^0.10.0
  google_mlkit_face_detection: ^0.8.0
  google_mlkit_face_mesh_detection: ^0.0.1
  google_mlkit_image_labeling: ^0.9.0
  google_mlkit_language_id: ^0.8.0
  google_mlkit_object_detection: ^0.10.0
  google_mlkit_pose_detection: ^0.9.0
  google_mlkit_selfie_segmentation: ^0.5.0
  google_mlkit_smart_reply: ^0.8.0
  google_mlkit_text_recognition: ^0.10.0
  google_mlkit_translation: ^0.8.0
  image_gallery_saver: ^2.0.3
  permission_handler: ^10.4.3
  image: ^3.1.3
  processing_camera_image: ^0.0.9


dev_dependencies:
  flutter_lints: ^2.0.2
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/ml/
    - assets/images/